/*
 * Module: polygon_dragger
 *
 * A PolygonDragger draws the control polygon of a cubic bezier curve.
 *
 */


/* requireJS module definition */
define(["util", "scene"], 
       (function(Util,Scene) {

    "use strict";

    /*
     * A polygon dragger draws the control polygon of a cubic bezier curve. 
     * Parameters:
     *
     * - getP [ function() --> [x,y] ]
     *
     *   an array of callback functions, one for each control point; the callbacks 
     *   will return the coordinates of each point as an array [x,y]
     *
     * - setPos [ function(dragEvent) ]
     *
     *        a callback function that repositions the dragger according to a 
     *        drag event generated by SceneController. The drag event is of the form 
     *        { position: [x,y], delta: [x,y] }, where pos is the absolute position
     *        of the mouse, and delta is the difference vector pointing from 
     *        the last known dragging position to the current mouse position.
     *
     * - drawStyle [ {radius: 5, width: 2, color: "#FF00FF"} ] 
     *
     *        specification object for the drawing style, example see above 
     * 
     */

    var PolygonDragger = function(getP, drawStyle) {

        // remember the callbacks
        this.getP = getP;
        
        // default draw style for the dragger
        drawStyle = drawStyle || {};
        this.drawStyle = drawStyle;
        this.drawStyle.width = drawStyle.width || 1;
        this.drawStyle.color = drawStyle.color || "#999999";
        
        // attribute queried by SceneController to recognize draggers
        this.isDragger = true; 
                                        
    };

    /*
     * draw the dragger, i.e. the control polygon
     */
    PolygonDragger.prototype.draw = function (context) {
        
        context.beginPath();
        var p = this.getP[0]();
        context.moveTo(p[0], p[1]);

        for (var i = 1; i < this.getP.length; i++) {
            p = this.getP[i]();
            context.lineTo(p[0], p[1]);
        }
        
        // draw style
        context.lineWidth   = this.drawStyle.width;
        context.strokeStyle = this.drawStyle.color;
        context.fillStyle   = this.drawStyle.color;
        
        // trigger the actual drawing
        context.stroke();
    };

    // this module exposes only the constructor for Dragger objects
    return PolygonDragger;

})); // define
