/*
 * JavaScript / Canvas teaching framwork 
 * (C)opyright Hartmut Schirmacher, hschirmacher.beuth-hochschule.de 
 *
 * Module: polygon_dragger
 *
 * TODO: Dok it all !!!
 *
 * A PolygonDragger is a drawable object than can react to 
 * events from a SceneController. It will typically control
 * the position of one vertex/point of a scene obejct.
 *
 */


/* requireJS module definition */
define(["util", "scene"], 
       (function(Util,Scene) {

    "use strict";

    /*
     * A dragger is a visible handle to move a 2D point around
     * using the 2D rendering features of the HTML5 canvas element. 
     * Parameters:
     *
     * - getPos [ function() --> [x,y] ]
     *
     *   callback function that will return the position of the dragger 
     *   as an array [x,y]
     *
     * - setPos [ function(dragEvent) ]
     *
     *        a callback function that repositions the dragger according to a 
     *        drag event generated by SceneController. The drag event is of the form 
     *        { position: [x,y], delta: [x,y] }, where pos is the absolute position
     *        of the mouse, and delta is the difference vector pointing from 
     *        the last known dragging position to the current mouse position.
     *
     * - drawStyle [ {radius: 5, width: 2, color: "#FF00FF", fill: false} ] 
     *
     *        specification object for the drawing style, example see above 
     * 
     */

    // var PolygonDragger = function(getP0, getP1, getP2, getP3, drawStyle) {
    var PolygonDragger = function(getP0, getP1, getP2, getP3) {

        // remember the callbacks
        this.getP0 = getP0;
        this.getP1 = getP1;
        this.getP2 = getP2;
        this.getP3 = getP3;
        
        // default draw style for the dragger
        this.drawStyle = {};
        this.drawStyle.width = 1;
        this.drawStyle.color = "#999999";
        
        // attribute queried by SceneController to recognize draggers
        this.isDragger = true; 
                                        
    };

    /*
     * draw the dragger as a small circle
     */
    PolygonDragger.prototype.draw = function (context) {

        var p0 = this.getP0();
        var p1 = this.getP1();
        var p2 = this.getP2();
        var p3 = this.getP3();

        context.beginPath();
        context.moveTo(p0[0], p0[1]);
        context.lineTo(p1[0], p1[1]);
        context.lineTo(p2[0], p2[1]);
        context.lineTo(p3[0], p3[1]);

        // var p = []
        // p.push(this.getP0());
        // p.push(this.getP1());
        // p.push(this.getP2());
        // p.push(this.getP3());

        // context.beginPath();
        // context.moveTo(p[0][0], p[0][1]);
        // for (var i = 1; i < p.length; i++) {
        //     context.lineTo(p[i][0], p[i][1]);
        // }
        
        // draw style
        context.lineWidth   = this.drawStyle.width;
        context.strokeStyle = this.drawStyle.color;
        context.fillStyle   = this.drawStyle.color;
        
        // trigger the actual drawing
        context.stroke();
    };

    // PolygonDragger.prototype.isHit = function (context,mousePos) {
    //     return false;
    // };

    // PolygonDragger.prototype.mouseDrag = function (dragEvent) {

    // };

    // this module exposes only the constructor for Dragger objects
    return PolygonDragger;

})); // define
