/*
 * JavaScript / Canvas teaching framwork 
 * (C)opyright Hartmut Schirmacher, hschirmacher.beuth-hochschule.de 
 *
 * Module: polygon_dragger
 *
 * TODO: Dok it all !!!
 *
 * A PolygonDragger is a drawable object than can react to 
 * events from a SceneController. It will typically control
 * the position of one vertex/point of a scene obejct.
 *
 */


/* requireJS module definition */
define(["util", "scene"], 
       (function(Util,Scene) {

    "use strict";

    /*
     * A dragger is a visible handle to move a 2D point around
     * using the 2D rendering features of the HTML5 canvas element. 
     * Parameters:
     *
     * - getPos [ function() --> [x,y] ]
     *
     *   callback function that will return the position of the dragger 
     *   as an array [x,y]
     *
     * - setPos [ function(dragEvent) ]
     *
     *        a callback function that repositions the dragger according to a 
     *        drag event generated by SceneController. The drag event is of the form 
     *        { position: [x,y], delta: [x,y] }, where pos is the absolute position
     *        of the mouse, and delta is the difference vector pointing from 
     *        the last known dragging position to the current mouse position.
     *
     * - drawStyle [ {radius: 5, width: 2, color: "#FF00FF", fill: false} ] 
     *
     *        specification object for the drawing style, example see above 
     * 
     */

    // var PolygonDragger = function(getP0, getP1, getP2, getP3, drawStyle) {
    // var PolygonDragger = function(getP0, getP1, getP2, getP3) {
    var PolygonDragger = function(getP) {

        // remember the callbacks
        this.getP = getP;

        // this.getP0 = getP0;
        // this.getP1 = getP1;
        // this.getP2 = getP2;
        // this.getP3 = getP3;
        
        // default draw style for the dragger
        this.drawStyle = {};
        this.drawStyle.width = 1;
        this.drawStyle.color = "#999999";
        
        // attribute queried by SceneController to recognize draggers
        this.isDragger = true; 
                                        
    };

    /*
     * draw the dragger, i.e. the control polygon
     */
    PolygonDragger.prototype.draw = function (context) {
        
        context.beginPath();
        var p = this.getP[0]();
        context.moveTo(p[0], p[1]);

        for (var i = 1; i < this.getP.length; i++) {
            p = this.getP[i]();
            context.lineTo(p[0], p[1]);
        }
        
        // draw style
        context.lineWidth   = this.drawStyle.width;
        context.strokeStyle = this.drawStyle.color;
        context.fillStyle   = this.drawStyle.color;
        
        // trigger the actual drawing
        context.stroke();
    };

    // PolygonDragger.prototype.isHit = function (context,mousePos) {
    //     return false;
    // };

    // PolygonDragger.prototype.mouseDrag = function (dragEvent) {

    // };

    // this module exposes only the constructor for Dragger objects
    return PolygonDragger;

})); // define
